proc compare base=output.allergy compare=input.allergy;
run;
proc compare base=output.condition compare=input.condition;
run;
proc compare base=output.encounter compare=input.encounter;
run;
proc compare base=output.lab compare=input.lab;
run;
proc compare base=output.location compare=input.location;
run;
proc compare base=output.medication compare=input.medication;
run;
proc compare base=output.patient compare=input.patient;
run;
proc compare base=output.practitioner compare=input.practitioner;
run;
proc compare base=output.procedure compare=input.procedure;
run;
proc compare base=output.vital_sign compare=input.vital_sign;
run;
proc compare base=ands.cohort compare=cohort;
run;
proc compare base=ands.hru compare=hru;
run;
proc compare base=ands.os compare=os;
run;
proc compare base=ands.trt_pattern compare=trt_pattern;
run;
proc compare base=ands.vital_sign_analysis compare=vital_sign;
run;